allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: false
  workerd: true
minimumReleaseAge: 4320

blockExoticSubdeps: true

trustPolicy: "no-downgrade"

strictDepBuilds: true

ignoreScripts: true
